version: "2"
services:
  eureka-server-peer1:
    image: adamkapuscinsky/ma-thesis-eureka-server
    container_name: eureka-server-peer1
    ports:
      - "8761:8761"
    networks:
      - network-eureka
  eureka-client-peer1:
    image: adamkapuscinsky/ma-thesis-eureka-client
    container_name: eureka-client-peer1
    environment:
      - ENVIRONMENT_HOST=eureka-server-peer1
    ports:
      - "28880:28880"
    networks:
      - network-eureka
  eureka-client-peer2:
    image: adamkapuscinsky/ma-thesis-eureka-client
    container_name: eureka-client-peer2
    environment:
      - ENVIRONMENT_HOST=eureka-server-peer1
      - port=28881
    ports:
      - "28881:28881"
    networks:
      - network-eureka
  eureka-client-peer3:
    image: adamkapuscinsky/ma-thesis-eureka-client
    container_name: eureka-client-peer3
    environment:
      - ENVIRONMENT_HOST=eureka-server-peer1
      - port=28882
    ports:
      - "28882:28882"
    networks:
      - network-eureka
  gateway:
    image: adamkapuscinsky/ma-thesis-gateway
    container_name: gateway
    environment:
      - ENVIRONMENT_HOST=eureka-server-peer1
    ports:
      - "8088:8088"
    networks:
      - network-eureka
networks:
  network-eureka: