version: "3"
services:
  eureka-server-peer1:
    image: adamkapuscinsky/ma-thesis-eureka-server
    container_name: eureka-server-peer1
    ports:
      - "8761:8761"
    restart: always
    networks:
      - network-eureka
  eureka-client-peer1:
    image: adamkapuscinsky/ma-thesis-eureka-client-serviceone
    container_name: eureka-client-peer1
    environment:
      - ENVIRONMENT_HOST=eureka-server-peer1
    ports:
      - "28880:28880"
    networks:
      - network-eureka
  eureka-client-peer2:
    image: adamkapuscinsky/ma-thesis-eureka-client-serviceone
    container_name: eureka-client-peer2
    environment:
      - APPLICATION_NAME=servicetwo
      - ENVIRONMENT_HOST=eureka-server-peer1
    ports:
      - "28881:28880"
    networks:
      - network-eureka
  eureka-client-peer3:
    image: adamkapuscinsky/ma-thesis-eureka-client-serviceone
    container_name: eureka-client-peer3
    environment:
      - APPLICATION_NAME=servicethree
      - ENVIRONMENT_HOST=eureka-server-peer1
    ports:
      - "28882:28880"
    networks:
      - network-eureka
  api:
    image: adamkapuscinsky/ma-thesis-load-balancer
    container_name: api
    environment:
      - ENVIRONMENT_HOST=eureka-server-peer1
    ports:
      - "8080:8080"
    restart: always
    networks:
      - network-eureka
  client:
    links:
      - api
    image: adamkapuscinsky/ma-thesis-front
    restart: on-failure
    container_name: client
    ports:
      - "4200:80"
    networks:
      - network-eureka
networks:
  network-eureka:
