server:
  port: ${port:8080}
spring:
  application:
    name: loadbalancer
eureka:
  client:
    service-url:
      defaultZone: http://${ENVIRONMENT_HOST:localhost}:8761/eureka
#    register-with-eureka: false
#logging:
#  level:
#    root: debug
