spring:
  application:
    name: serviceone
server:
  port: ${port:28880}
eureka:
  instance:
    lease-renewal-interval-in-seconds: 10
  client:
    serviceUrl:
      defaultZone: http://${ENVIRONMENT_HOST:localhost}:8761/eureka
request:
  loading:
    time:
      profile: ${REQUEST_LOADING_TIME:short}
#
#request:
#  loading:
#    time: ${REQUEST_LOADING_TIME:10}
