spring:
  application:
    name: ${APPLICATION_NAME:serviceone}
server:
  port: ${PORT:28880}
eureka:
  instance:
    lease-renewal-interval-in-seconds: 10
  client:
    serviceUrl:
      defaultZone: http://${ENVIRONMENT_HOST:localhost}:8761/eureka
